#!/bin/bash
#script for backing up files in current directory
#without arguments backs up all files in current directory
#with filename as argument backs up that file

# pri predani parametru -x provede zapnuti debug logu
if [ "$1" = "-x" ]
then
	set -x
fi

v_backupDir=".backup"
v_currentDate=$(date +%F)
v_currentDateTime=$(date +%F_%H-%M)
v_dailyBackupFile=backup--"$v_currentDate".zip
v_dailySnapshotFile=snapshot--"$v_currentDate".zip
v_manualSnapshotFile=snapshot--"$v_currentDateTime".zip
v_manualSnapshotComment=snapshot--"$v_currentDateTime".txt
v_monthNo="$(date +%Y.%m)"
v_archiveFile="archive-${v_monthNo}.zip"
v_returnBack=0

f_check_files()
{
	#checks folder for presence of files
	if [ "$(find . -maxdepth 1 -type f | wc -l)" -eq 0 ]
	then
		echo "no file in current directory, check or set your location ($PWD)"
		exit 1
	fi

	if [ ! -d "$PWD/"$v_backupDir"" ]
	then
		mkdir "$v_backupDir"
		echo "first backup - created backup directory "$v_backupDir""
	fi
}

f_archive()
{
	#adds all previous snapshot files to .backup/archive.zip and deletes them
	find "$v_backupDir" -type f -mtime +7 -name "*--*.zip"\
		-exec zip -T --move "$v_backupDir"/$v_archiveFile {} \;

	#adds all previous snapshot comment files to .backup/archive.zip and deletes them
	find "$v_backupDir" -type f -mtime +7 \! -name "*.zip" -name "*--*.txt"\
		-exec zip -T --move "$v_backupDir"/$v_archiveFile {} \;

	#adds daily modifications from current day to daily backup archive
	#and deletes them
	find "$v_backupDir" -type f \! -name "*.zip" \! -name "*.txt" -name "*--*"\
		-exec zip -T --move "$v_backupDir"/"$v_dailyBackupFile" {} \;

	#deletes archive files older than 6 months
	find "$v_backupDir" -type f -mtime +180 -name "archive*.zip" -exec rm {} \; -print
}


f_backup()
{
	#checks daily snapshot file, if not pressent it calls f_snapshot function
	if [ ! -f "$v_backupDir"/"$v_dailySnapshotFile" ]
	then
		echo "creating daily snapshot ($v_dailySnapshotFile)"
		find "$v_backupDir" -maxdepth 1 -mindepth 1 -type f \! -name "*--*" \! -name "*.zip"\
			-exec zip -T "$v_backupDir"/"$v_dailySnapshotFile" {} \;
		echo "daily snapshot created"
	fi

	echo "backing up all changed files"
	find . -maxdepth 1 -mindepth 1 -type f\
		-exec cp -aub --suffix="--$v_currentDateTime" {} "$v_backupDir"/ \;
}

f_snapshot()
{
		echo -e "write message you want to be added into snapshot\n"
		vim "$v_backupDir"/"$v_manualSnapshotComment"
		echo "creating snapshot ($v_manualSnapshotFile)"
		find . -maxdepth 1 -mindepth 1 -type f -exec zip -T "$v_backupDir"/"$v_manualSnapshotFile" {} \;
		echo "snapshot created"
}

#allows user to add parameter (-c) to create snapshot and add comment it
case $1 in
	-h|--help)
		echo -e "usage:\n\
					-c|--comment	-	create snapshot and set comment, which will be stored in zip archive\n\
					-h|--help		-	prints this message\n\
					"
		;;
	-c|--comment)
		#allows user to add message into file, which will be added into zip archive
		f_check_files
		f_snapshot
		f_backup
		f_archive
		;;
	*)
		f_check_files
		f_backup
		f_archive
		;;
esac

exit 0
