#!/bin/bash
#check-server
#script, ktery bude spousteny cronem a bude provadet nastavene kontroly na serveru


#LIST 
#_PROMENNE 
#_LOGOVANI 
#_PODMINKY 
#_KONFIGURACE 
#_MYSQL_BACKUP_CRON
#_LINKOVANI_SCRIPTU

#_PROMENNE
scriptName="check-server"

#seznam scriptu, ktere se budou spoustet z cron.daily, mysql-backup se bude spousten crontabem
defaultList="check-server server-backup rsync-backup postgresql-backup"


#v pripade, ze je script spousten ze slozky pracovni, nastavi se mu jine cesty, nez pri spusteni pres cron
if [ "$(echo $PWD | grep -c pracovni)" -eq 0 ] && [ "$(echo $0 | grep -c pracovni)" -eq 0 ]
then

	#cesta ke scriptu
	scriptDir="/usr/local/bash-scripts"
	verbose=0
else

	#cesta ke scriptu
	scriptDir="/usr/local/bash-scripts/pracovni"
	verbose=1
fi


#_LOGOVANI

#nacteni definice funkci Log,LogError,RvCheck,MailSend z knihovny
. $scriptDir/funkce 


#_PODMINKY
Log "zacatek scriptu"
echo "$$" > "$startFile"
Log "($startFile) set to ($$)"


#_KONFIGURACE

#zapise konfiguracni soubor, ze ktereho bude nasledne nacitat hodnoty
if [ -f "$configFile" ]
then
	#nacteni obsahu configfile
	. "$configFile"
	Log "nacten konfiguracni soubor ($configFile)"
else
	{
	echo "disabled=0	#slouzi pro globalni, hromadne zruseni spousteni vsech scriptu ze slozky $scriptDir"
	} > $configFile
	Log "zapsan konfiguracni soubor pro server ($HOSTNAME)"
	. "$configFile"
fi


#nastavenim disabled na 1 se vypne spousteni scriptu, uprav $configFile, mail se neposila
if [ "$disabled" -eq 1 ]
then
	Log "script byl disablovan v konfiguracnim souboru ($configFile)"
	exit 0
fi


#pro jistotu vzdy nastavi opravneni pro konfiguracni soubory na 600
chmod -R 600 "$configDir"


#_MYSQL_BACKUP_CRON
#pokud neni zaznam pro mysql-backup
if [ ! -e /etc/cron.d/mysql-backup ]
then
	#vytvori radek, ktery spousti dany script ve 20:00 a kompletni debug vystup se uklada do souboru ve /var/log
	{ 
		echo "#denni spousteni mysql-backup"
		echo "0 20 * * * root /bin/bash -x $scriptDir/mysql-backup &>$logDir/mysql-backup.log"
	} > /etc/cron.d/mysql-backup
	RvLog "zapsano spousteni mysql-backup scriptu do cronu roota"
#pokud uz zaznam existuje
else
	#a stale existuje link v /etc/cron.daily, tak ho odstrani
	if [ -e /etc/cron.daily/mysql-backup ]
	then
		rm /etc/cron.daily/mysql-backup
		RvLog "odstranen link z cron.daily pro mysql-backup"
	fi
fi


#_LINKOVANI_SCRIPTU
# nalinkovani scriptu do slozky /usr/local/sbin
for scriptPath in $(find "$scriptDir" -maxdepth 1 -mindepth 1 -type f | grep -v "funkce")
do
	script=$(basename "$scriptPath")
	if [ ! -h "$sbinDir"/"$script" ]
	then
		ln -sf "$scriptPath" "$sbinDir"/"$script"
		LogError "vytvoren symlink pro [$script]"
	else
		Log "symlink pro [$script] je v poradku"
	fi
done
Log "Dokoncena kontrola scriptu v "$sbinDir""


#pokud je errorFile, posle mailem $logFile, jinak udela touch na stopFile
MailSend
exit 0
