#!/bin/bash
#check-server
#script, ktery bude spousteny cronem a bude provadet nastavene kontroly na serveru


#LIST 
#_PROMENNE 
#_LOGOVANI 
#_PODMINKY 
#_KONFIGURACE 
#_CHECK_SERVER_CRON
#_LINKOVANI_SCRIPTU

# pri predani parametru -x provede zapnuti debug logu
if [ "$1" = "-x" ]
then
	set -x
fi

#_PROMENNE
scriptName="check-server"

#seznam scriptu, ktere se budou spoustet z cron.daily, mysql-backup se bude spousten crontabem
defaultList="check-server server-rsync-backup server-backup rsync-backup postgresql-backup"

#cesta ke scriptu
scriptDir="/usr/local/bash-scripts"
verbose=0
deBug=0


#_LOGOVANI

#nacteni definice funkci Log,LogError,RvCheck,MailSend z knihovny
. $scriptDir/funkce 


#_PODMINKY
Log "zacatek scriptu"
echo "$$" > "$startFile"
Log "($startFile) set to ($$)"


#_KONFIGURACE

#zapise konfiguracni soubor, ze ktereho bude nasledne nacitat hodnoty
if [ -f "$configFile" ]
then
	#nacteni obsahu configfile
	. "$configFile"
	Log "nacten konfiguracni soubor ($configFile)"
else
	{
	echo "disabled=0	#slouzi pro globalni, hromadne zruseni spousteni vsech scriptu ze slozky $scriptDir"
	} > $configFile
	Log "zapsan konfiguracni soubor pro server ($HOSTNAME)"
	. "$configFile"
fi


#nastavenim disabled na 1 se vypne spousteni scriptu, uprav $configFile, mail se neposila
if [ "$disabled" -eq 1 ]
then
	Log "script byl disablovan v konfiguracnim souboru ($configFile)"
	exit 0
fi


#pro jistotu vzdy nastavi opravneni pro konfiguracni soubory na 600
chmod -R 600 "$configDir"


#_CHECK_SERVER_CRON
#pokud neni zaznam pro check-server
if [ ! -e /etc/cron.d/check-server ]
then
	#vytvori radek, ktery spousti dany script ve 20:00 a kompletni debug vystup se uklada do souboru ve /var/log
	{ 
		echo "#denni spousteni check-server"
		echo "0 20 * * * root /bin/bash -x $scriptDir/check-server &>$logDir/check-server.log"
	} > /etc/cron.d/check-server
	RvLog "zapsano spousteni check-server scriptu do cronu roota"
fi


#_LINKOVANI_SCRIPTU
# nalinkovani scriptu do slozky /usr/local/sbin
for scriptPath in $(find "$scriptDir" -maxdepth 1 -mindepth 1 -type f | grep -v "funkce")
do
	script=$(basename "$scriptPath")
	if [ ! -h "$sbinDir"/"$script" ]
	then
		ln -sf "$scriptPath" "$sbinDir"/"$script"
		LogError "vytvoren symlink pro [$script]"
	else
		Log "symlink pro [$script] je v poradku"
	fi
done
Log "Dokoncena kontrola scriptu v "$sbinDir""


#pokud je errorFile, posle mailem $logFile, jinak udela touch na stopFile
MailSend
exit 0
