#!/bin/bash
#inicializacni script pro nahrani a nastaveni rsync stahovani na server
sbinDir="/usr/local/sbin"
btsyncDir="/var/btsync"
bashFile="$HOME/.bashrc"
# omezeni seznamu scriptu
#defaultList="server-backup zabbix-backup mysql-backup samba-backup rsync-backup postgresql-backup check-server"
defaultList="server-backup mysql-backup postgresql-backup check-server"


#_PROMENNE
scriptName="initialize"


#v pripade, ze je script spousten ze slozky pracovni, nastavi se mu jine cesty, nez pri spusteni pres cron
if [ "$(echo $PWD | grep -c pracovni)" -eq 0 ] && [ "$(echo $0 | grep -c pracovni)" -eq 0 ]	
then
	scriptDir="/usr/local/bash-scripts" #cesta ke scriptu
        verbose=0
	deBug=0
else
	scriptDir="/usr/local/bash-scripts/pracovni" #cesta ke scriptu
	verbose=1
	deBug=1
fi

#spousti se pouze pod rootem
if [ "$UID" -eq 0 ]
then
	#stazeni obsahu ze serveru
	git clone git@git.tlapnet.cz:vaclavz/bash-scripts.git /usr/local/
	echo "Provedeno stazeni souboru ze serveru Monitoring"
else
	echo "Pozor - prvotni spusteni je nutne spustit jako root"
fi


#_LOGOVANI
. "$scriptDir/funkce"
Log "Zacatek scriptu"
CheckDir "$pidDir"
echo "$$" > "$startFile"
RvLog "start file set to ($$)"

#spousti se pouze pod rootem
if [ "$UID" -eq 0 ]
then
	[ ! -d "$logFile" ] || rm -r "$logFile"
	RvLog "odstraneni stare slozky $logFile"
	Log "kontrolni cast scriptu"
	CheckDir "$configDir"
	CheckDir "$pidDir"
	CheckDir "$pipeDir"
	CheckDir "$scriptDir"
	CheckDir "$scripty"
	Log "nalinkovani scriptu do $sbinDir"
    #nalinkuje vsechny scripty ve slozce $scriptDir do slozky $sbinDir
	for script in $(find "$scriptDir" -maxdepth 1 -mindepth 1 -type f )
	do
		ln -sf "$script" "$sbinDir"
		RvLog "vytvoren symlink ($script)"

		#if [ -f "$btsyncDir/scripty/${script##*/}/.config" ]
		#then
		#	cp -a "$btsyncDir/scripty/${script##*/}/.config" "/usr/local/etc/${script##*/}.conf.old"
		#	Log "nalezen puvodni config, byl zkopirovan do (/usr/local/etc/${script##*/}.conf.old)"
		#else
		#	Log "konfigurace pro script ($script) nebyla nalezena"
		#fi
	done

	Log "konfigurace cronu a logrotate"
	[ -h "/etc/logrotate.d/scripty" -a -e "/etc/logrotate.d/scripty" ] ||\
        ln -sf /usr/local/bash-scripts/etc/logrotate.d/scripty /etc/logrotate.d/scripty	
	RvLog "ln -sf /usr/local/bash-scripts/etc/logrotate.d/scripty /etc/logrotate.d/scripty"


	#vytvoreni pole ze seznamu scriptu
	scriptsARRAY=($(echo "$defaultList"))
	Log "nacteno pole scriptsARRAY ($scriptsARRAY)"

	#doplneni aliasu scr
	if [ -e "$bashFile" ] && [ "$(grep -c 'alias scr' $bashFile)" -eq 0 ]
	then
		echo "alias scr='screen -d -R'" >> "$bashFile"
		RvLog "doplnen alias scr do ($bashFile)"
	else
		Log "soubor ($bashFile) je aktualni"
	fi
fi

MailSend
exit "$rv"
