#!/bin/bash
#inicializacni script pro nahrani a nastaveni rsync stahovani na server
sbinDir="/usr/local/sbin"
defaultList="server-backup mysql-backup postgresql-backup check-server"


#_PROMENNE
scriptName="initialize"


#v pripade, ze je script spousten ze slozky pracovni, nastavi se mu jine cesty, nez pri spusteni pres cron
if [ "$(echo $PWD | grep -c pracovni)" -eq 0 ] && [ "$(echo $0 | grep -c pracovni)" -eq 0 ]	
then
	scriptDir="/usr/local/bash-scripts" #cesta ke scriptu
	verbose=0
	deBug=0
else
	scriptDir="/usr/local/bash-scripts/pracovni" #cesta ke scriptu
	verbose=1
	deBug=1
fi

#spousti se pouze pod rootem
if [ "$UID" -eq 0 ]
then
	# pokud jeste neexistuje slozka se scripty, provede klonovani repozitare
	if [ ! -d "$scriptDir" ]
	then
		#stazeni obsahu ze serveru
		git clone git@git.tlapnet.cz:vaclavz/bash-scripts.git "$scriptDir"
		echo "Provedeno oklonovani git repozitare"
	# pokud uz slozka existuje, prepne se do ni a udela pull
	else
		cd "$scriptDir"
		git pull
		echo "Provedeno oklonovani git repozitare"
		cd -
	fi
else
	echo "Pozor - spusteni je nutne provest jako root"
	exit 1
fi


#_LOGOVANI
# nacteni konfiguracniho souboru s funkcemi
. "$scriptDir/funkce"
Log "Zacatek scriptu"

CheckDir "$pidDir"
echo "$$" > "$startFile"
RvLog "start file set to ($$)"

#spousti se pouze pod rootem
if [ "$UID" -eq 0 ]
then
	Log "kontrolni cast scriptu"
	CheckDir "$configDir"
	CheckDir "$pidDir"
	CheckDir "$pipeDir"
	CheckDir "$scriptDir"
	CheckDir "$scripty"
	CheckDir "$logDir"

	Log "nalinkovani scriptu do $sbinDir"

    #nalinkuje vsechny scripty ve slozce $scriptDir do slozky $sbinDir
	for script in $(find "$scriptDir" -maxdepth 1 -mindepth 1 -type f | grep -v "funkce" )
	do
		ln -sf "$script" "$sbinDir"
		RvLog "vytvoren symlink ($script)"
	done

	Log "konfigurace cronu a logrotate"
	# nalinkovani logrotate pro scripty
	ln -sf "$scriptDir"/etc/logrotate.d/scripty /etc/logrotate.d/scripty	
	RvLog "ln -sf $scriptDir/etc/logrotate.d/scripty /etc/logrotate.d/scripty"
fi

MailSend
exit "$rv"
