#!/bin/bash
#mysql-backup
#provadi mysql dumpy zvolenych databazi

VERSION_MAJOR=1
VERSION_MINOR=0
VERSION_PATCH=0
VERSION="$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH"

#LIST
#_PROMENNE
#_EXITY
#_LOGOVANI
#_PODMINKY
#_KONFIGURACE
#_MYSQL_BACKUP_CRON
#_ZALOHA

# pri predani parametru -x provede zapnuti debug logu
if [ "$1" = "-x" ]
then
	set -x
fi

# vypsani verze
if [ "$1" = "-V" -o "$1" = "--version" ]
then
	echo "$VERSION"
	exit 0
fi

#_PROMENNE
scriptName="mysql-backup"
backupDir="/var/backup/mysql"
backupLimit=14
todayDateTime="$(date +%F_%H-%M)"
mysqlPassword="EMPTY"

#cesta ke scriptu
scriptDir="/usr/local/bash-scripts"
verbose=0
deBug=0


#_EXITY
#exit 1		#disablovany script
#exit 2		#spatne nastavena nektera z promennych


#_LOGOVANI

#nacteni definice funkci Log,LogError,RvLog,MailSend z knihovny
. $scriptDir/funkce	
Log "script ($scriptName) - zacatek"
echo "$$" > "$startFile"
Log "($startFile) set to ($$)"

#konfigurace pro soubor s heslem
mysqlDefaultsFile="$configDir/.my.cnf"


#funkce pro zapis souboru pro mysqldump
write_mysqlDefaultsFile()
{
	{
		# musi tu byt i sekce mysql, protoze se vycitaji databaze
		echo "[mysql]"
		echo "user=root"
		echo "password='$mysqlPassword'"
		echo "default-character-set=utf8mb4"
		echo ""
		echo "[mysqldump]"
		echo "user=root"
		echo "password='$mysqlPassword'"
		echo "default-character-set=utf8mb4"
	} > "$mysqlDefaultsFile"
	chmod 600 "$mysqlDefaultsFile"

	if [ -f "$configFile" ]
	then
		#odstranit radky z configFile
		sed -i -e 's/mysqlUser.*//g' "$configFile"
		sed -i -e 's/mysqlPassword.*//g' "$configFile"
		sed -i -e 's/backupItems.*//g' "$configFile"
	fi
}


#_KONFIGURACE
#zapise konfiguracni soubor, ze ktereho bude nasledne nacitat hodnoty
write(){
	if [ -f "$configFile" ]
	then
		cp "$configFile" "${configFile}.back"
		RvLog "provedena zaloha konfigurace do (${configFile}.back)"
	fi
	{
	echo "disabled=1		#vypne/zapne (1/0) provadeni scriptu"
	echo "backupLimit=14		#nastavuje, kolik zaloh zpetne se bude drzet"
	} > "$configFile"
	LogError "zapsan konfiguracni soubor pro server ($HOSTNAME)"
	write_mysqlDefaultsFile
}

#_MYSQL_BACKUP_CRON
#pokud neni zaznam pro mysql-backup
if [ ! -e /etc/cron.d/mysql-backup ]
then
	#vytvori radek, ktery spousti dany script ve 2:00 a kompletni debug vystup se uklada do souboru ve /var/log
	{ 
		echo "#denni spousteni mysql-backup"
		echo "0 2 * * * root $sbinDir/mysql-backup &>$outputFile"
	} > /etc/cron.d/mysql-backup
	RvLog "zapsano spousteni mysql-backup scriptu do cronu"
fi


#pokud neni konfiguracni soubor, nebo byl predan parametr -c
if [ ! -f "$configFile" ] || [ "$1" = "-c" ]
then
	write
	MailSend
	exit 10
fi

if [ -f "$configFile" ]
then
	. "$configFile"
	Log "nacten konfiguracni soubor ($configFile)"
else
	write
	. "$configFile"
fi


#nastavenim disabled na 1 se vypne spousteni scriptu, uprav $configFile, mail se neposila
if [ "$disabled" -eq 1 ]
then
	Log "script ($scriptName) byl disablovan v konfiguracnim souboru ($configFile)"
	MailSend
	exit 1
fi


#kontrola existence mysqlDefaultsFile, pripadne vytvoreni z existujiciho configu
#v pripade prazdneho hesla zaloguje error
if [ ! -f "$mysqlDefaultsFile" ] && [ -n "$mysqlPassword" ]
then
	write_mysqlDefaultsFile
else
	if [ -z "$mysqlPassword" ]
	then
		LogError "Promenna mysqlPassword je prazdna, \
					je nutne nastavit heslo do mysql databaze v [$mysqlDefaultsFile]"
		write_mysqlDefaultsFile
		MailSend
		exit 12
	fi
fi


#kontrola, zda mysqlPassword neobsahuje EMPTY
if [ $(grep -c "EMPTY" "$mysqlDefaultsFile") -ne 0 ]
then
	LogError "POZOR, neni nastaveno heslo pro mysql-backup v [$mysqlDefaultsFile]"
	MailSend
	exit 13
fi


#_ZALOHA
#zkontroluje slozku pro zalohy
CheckDir "$backupDir"
# kontrola slozky pro export uzivatelu a opravneni + zaloh databaze jako takove
CheckDir "$backupDir/mysql"

#vyliti uzivatelu z mysql vcetne opravneni - uklada se do slozky /var/backup/mysql/mysql/user-export-datum-cas.sql
#naleva se to mysql -A < user-export-*.sql
mysql --defaults-extra-file="$mysqlDefaultsFile" -B -N -e\
	"SELECT DISTINCT CONCAT('SHOW GRANTS FOR \'', user, '\'@\'', host, '\';') AS query FROM mysql.user" |\
	mysql --defaults-extra-file="$mysqlDefaultsFile" |\
	sed -e 's/\(GRANT .*\)/\1;/;s/^\(Grants for .*\)/## \1 ##/;/##/{x;p;x;}' -e 's/\\\\/\\/g' |\
	grep -v "root" > "$backupDir"/mysql/user-export-"${todayDateTime}".sql
RvLog "Zaloha uzivatelu a opravneni z mysql databaze"

#nactou se vsechny databaze, ktere nemaji v nazvu Database nebo _schema
backupItems=$(mysql --defaults-file="$mysqlDefaultsFile"\
				-s -e "show databases;" | grep -v "Database" | grep -v "_schema\|zabbix" | tr '\n' ' ')
RvLog "nacteni databazi pro zalohovani"
#ze seznamu databazi oddeleneho mezerou se vytvori pole
backupARRAY=($(echo "$backupItems"))
RvLog "nastaveno pole backupARRAY, pocet databazi pro zalohovani je (${#backupARRAY[@]})"

#kontroluje, zda pole neni prazdne, coz nesmi nastat nikdy. Databaze mysql je vzdy pritomna.
backupArrayLength=${#backupARRAY[@]}
if [ "$backupArrayLength" -eq 0 ]
then
	LogError "POZOR - nacteny seznam databazi je prazdny"
fi


for database in ${backupARRAY[@]}
do
	backupName="$database-${todayDateTime}"
	backupPath="$backupDir/$database"
	CheckDir "$backupDir/$database"
	#doplneny parametry -e -F --routines
	#-e extended-insert - viceradkove inserty = mensi dump a rychlejsi naliti
	#-F flush-logs
	#--routines - dumpuje i funkce, rutiny a dalsi chujoviny
	mysqldump --defaults-extra-file="$mysqlDefaultsFile" "$database"\
			  -e -F --routines --events --add-locks -r "$backupPath/${backupName}.sql" > /dev/null
	RvLog "Vytvoren mysqldump databaze s nazvem ($backupPath/${backupName}.sql)"

	if [ "$?" -eq 0 ] && cd "$backupPath"
	then
		#-T otestuje archiv a --move po uspesnem testu soubor smaze
		zip -T -m "${backupName}.zip" "${backupName}.sql" > /dev/null
		RvLog "mysqldump uspesne zkomprimovan (${backupName}.zip)"
	fi

	# udela i slave dump, aby byl pripraveny pro pripad potreby
	mysqldump --defaults-extra-file="$mysqlDefaultsFile" "$database"\
			  --master-data=1 --ignore-table=radius.radacct --ignore-table=radius.radpostauth \
			  --ignore-table=radius.pwd_history --ignore-table=radius.mail_notification \
			  -F --routines --events --add-locks -r "$backupPath/slave-${backupName}.sql" > /dev/null
	RvLog "Vytvoren mysqldump databaze s nazvem ($backupPath/slave-${backupName}.sql)"

	if [ "$?" -eq 0 ] && cd "$backupPath"
	then
		#-T otestuje archiv a --move po uspesnem testu soubor smaze
		zip -T -m "slave-${backupName}.zip" "slave-${backupName}.sql" > /dev/null
		RvLog "mysqldump uspesne zkomprimovan (slave-${backupName}.zip)"
	fi

	#kontroluje, zda pocet zaloh neni mensi nez backuplimit - pokud prestane zalohovat, tak nesmi mazat stare
	if [ $(find "$backupPath" -name "*.zip" | wc -l) -gt "$backupLimit" ]
	then
		#odstraneni zaloh starsich nez $backupLimit
		find "$backupPath" -type f -mtime +"$backupLimit" -exec rm {} \;
		RvLog "odstraneni starych zaloh z ($backupPath)"
	fi
done


MailSend
exit 0
