#!/bin/bash
#server-rsync-backup - provadi zalohovani serveru vuci jinemu rsync serveru na port 873
#umoznuje v konfigu zvolit, zda je overovany, nebo ne

#LIST
#_PROMENNE
#_EXITY
#_LOGOVANI
#_PODMINKY
#_KONFIGURACE
#_ZALOHA

# pri predani parametru -x provede zapnuti debug logu
if [ "$1" = "-x" ]
then
	set -x
fi

#_PROMENNE
#promenne se nastavuji v $config souboru, ktery se nacte, pokud existuje

#promenne, ktere by se moc menit nemely, ale ve vysledku je to burt
scriptName="server-rsync-backup"
backupDir="/var/backup"

#dnesni datum ve formatu YYYY-MM-DD
todayDate="$(date +%F)"	

#cesta ke scriptu
scriptDir="/usr/local/bash-scripts"
verbose=0
deBug=0


#_EXITY
#exit 1		#spatne nastavena promenna
#exit 2		#zapsan defaultni konfiguracni soubor
#exit 3		#nebyl nastaven cil zaloh


#_LOGOVANI

#nacteni definice funkci Log,LogError,RvLog,MailSend z knihovny
. $scriptDir/funkce	
Log "script ($scriptName) - zacatek"
echo "$$" > "$startFile"
Log "($startFile) set to ($$)"


#_KONFIGURACE
#zapise konfiguracni soubor, ze ktereho bude nasledne nacitat hodnoty
write(){
	echo "#disabled=1 - script se nepousti
#disabled=0 - script se pousti
disabled=1

#cil, kam se bude zalohovat, tzn user@server:
rsyncTarget=\"uzivatel@ip.ad.re.sa:c/es/ta\"
" > "$configFile"

	RvLog "{write} - zapsan konfiguracni soubor pro server ($HOSTNAME)"
}


# kontrola cron souboru
#pokud neni zaznam pro server-rsync-backup
if [ ! -e /etc/cron.d/server-rsync-backup ]
then
	#vytvori radek, ktery spousti dany script ve 2:00 a kompletni debug vystup se uklada do souboru ve /var/log
	{ 
		echo "#denni spousteni server-rsync-backup"
		echo "0 4 * * * root $sbinDir/server-rsync-backup &>$outputFile"
		echo "0 23 * * * root $sbinDir/server-rsync-backup &>$outputFile"
	} > /etc/cron.d/server-rsync-backup
	RvLog "zapsano spousteni server-rsync-backup scriptu do cronu"
fi


#pokud existuje konfiguracni soubor, tak ho zkusi nacist
if [ -f "$configFile" ]
then
	. "$configFile"
	Log "nacten konfiguracni soubor ($configFile)"
#pokud konfiguracni soubor neexistuje, tak zapise novy
else
	write
	LogError "zapsan cisty konfiguracni soubor"
	MailSend
	exit 2
fi


#pri prvotnim spusteni je script defaultne disablovany
if [ "$disabled" -eq 1 ]
then
	Log "script ($scriptName) je disablovany v ($configFile)"
	MailSend
	exit 0
fi


#kontrola nastaveni cile pro zalohovani, pokud obsahuje defaultni retezec, nebo je prazdna, pak zaloguje error a skonci
if [ $(echo "$rsyncTarget" | grep -c "ip.ad.re.sa") -ne 0 ] || [ -z "$rsyncTarget" ]
then
	LogError "nebyl nastaven cil zalohovani v souboru [$configFile], promenna rsyncTarget"
	MailSend
	exit 3
else
	Log "zaloha se provede na [$rsyncTarget]"
fi


Log "Zacatek zalohovani"


#pokud je nastavena promena s uzivatelem, pak se bude vuci serveru autentifikovat
#verbose vystup zalohovanych souboru je v /var/log/server-rsync-backup.log
Log "rsync s overenim uzivatele -> [$rsyncTarget]"
rsync -rlt --delete --bwlimit=50M /var/backup/* "$rsyncTarget" > "$logDir/${scriptName}.log"
RvLog "dokoncen rsync -> [$rsyncUser@$rsyncTarget]"
rv="$?"


#osetreni erroru navratovych hodnot
case "$rv" in
	1)
		LogError "Problem s overenim, zkontroluj dostupnost serveru"
		;;
	5)
		LogError "zkontroluj, zda neni problem s cestou k cili, zda neni potreba uzivatel,"
		LogError " nebo je parovani klicu v poradku"
		;;
	20)
		LogError "rsync byl ustrelen SIGHUP, nebo neco podobneho"
		;;
	0)
		Log "navratova hodnota je 0, tedy zalohovani probehlo bez potizi"
		;;
esac

MailSend
Log "OK - ($scriptName) zalohovani dokonceno"
exit 0
