#!/bin/bash
#zabbix-backup
#provadi mysql dupmove zalohy pro zvolenou sluzbu a zastavuje service


#LIST _PROMENNE _EXITY _LOGOVANI _PODMINKY _KONFIGURACE _ZALOHA


#_PROMENNE
scriptName="zabbix-backup"
backupDir="/var/backup/zabbix"
todayDate="$(date +%F)"
#konfigurace pro soubor s heslem
mysqlPassword="EMPTY"

#cesta ke scriptu
scriptDir="/usr/local/bash-scripts"
verbose=0
deBug=0


#_EXITY
#exit 1	#script byl disablovan v konfiguracnim souboru
#exit 2	#nebyla nastavena nektera z potrebnych promennych v $configFile


#_LOGOVANI

#nacteni definice funkci Log,LogError,RvLog,MailSend z knihovny
. $scriptDir/funkce	
Log "script ($scriptName) - zacatek"
echo "$$" > "$startFile"
Log "($startFile) set to ($$)"


#_KONFIGURACE


#funkce pro zapis souboru pro mysqldump
write_mysqlDefaultsFile()
{
	{
	echo "[mysql]"
	echo "user=zabbix"
	echo "password='$mysqlPassword'"
	echo ""
	echo "[mysqldump]"
	echo "user=zabbix"
	echo "password='$mysqlPassword'"
	} > "$mysqlDefaultsFile"
	chmod 600 "$mysqlDefaultsFile"

	if [ -f "$configFile" ]
	then
	#odstranit radky z configFile
	sed -i -e 's/mysqlUser.*//g' "$configFile"
	sed -i -e 's/mysqlPassword.*//g' "$configFile"
	sed -i -e 's/backupItems.*//g' "$configFile"
	fi
}


#zapise konfiguracni soubor, ze ktereho bude nasledne nacitat hodnoty
write(){
	if [ -f "$configFile" ]
	then
	cp "$configFile" "${configFile}.back"
	RvLog "provedena zaloha konfigurace do (${configFile}.back)"
	fi	
	{
	echo "disabled=1	#vypne/zapne (1/0) provadeni scriptu"
	echo "backupLimit=7	#nastavuje, kolik zaloh zpetne se bude drzet"
	echo "backupItem=\"zabbix\"	#seznam databazi oddeleny mezerou"
	echo "serviceArray=( zabbix-server httpd )	#seznam sluzeb, ktere se budou zastavovat oddeleny mezerou"
	} > "$configFile"
	LogError "zapsan konfiguracni soubor pro server ($HOSTNAME)"
	write_mysqlDefaultsFile
}


mysqlDefaultsFile="$configDir/.my-zabbix.cnf"
#kontrola existence mysqlDefaultsFile, pripadne vytvoreni z existujiciho configu
#v pripade prazdneho hesla zaloguje error
if [ ! -f "$mysqlDefaultsFile" ]
then
	write_mysqlDefaultsFile
else
	if [ -z "$mysqlPassword" ]
	then
		LogError "Promenna mysqlPassword je prazdna, je nutne nastavit heslo do mysql databaze v [$mysqlDefaultsFile]"
		write_mysqlDefaultsFile
		MailSend
		exit 12
	fi
fi


#nacteni $configFile, pripadne zapsani defaultniho
if [ -f "$configFile" ]
then
	. "$configFile"
	Log "nacten konfiguracni soubor ($configFile)"
else
	write
	. "$configFile"
fi


#nastavenim disabled na 1 se vypne spousteni scriptu, uprav $configFile, mail se neposila
if [ "$disabled" -eq 1 ]
then
	Log "script ($scriptName) byl disablovan v konfiguracnim souboru ($configFile)"
	exit 1
fi


#kontrola nastaveni promennych z configu
if [ -z "$backupItem" ] || [ -z "$serviceArray" ]
then
	LogError "nebyla nastavena nektera z promennych backupItem=($backupItem), serviceArray=($serviceArray)"
	exit 2
fi


#kontrola, zda mysqlPassword neobsahuje EMPTY
if [ $(grep -c "EMPTY" "$mysqlDefaultsFile") -ne 0 ]
then
	LogError "POZOR, neni nastaveno heslo pro mysql-backup v [$mysqlDefaultsFile]"
	MailSend
	exit 13
fi


Log "zacatek zalohovani - zastaveni sluzeb"


#zastaveni pozadovanych sluzeb
for serviceName in ${serviceArray[@]}
do
	/bin/systemctl stop "$serviceName"
	RvLog "zastaveni sluzby ($serviceName)"
	sleep 1
done


#_ZALOHA
backupName="$backupItem-${todayDate}.sql"
RvLog "nastaven promenna backupName=($backupName)"
CheckDir "$backupDir"


#vytvoreni mysqldumpu
mysqldump --defaults-extra-file="$mysqlDefaultsFile" -e -F --routines "$backupItem" -r "$backupDir/$backupName"
RvLog "Vytvoren mysqldump databaze s nazvem ($backupDir/$backupName)"

#kontrola navratove hodnoty mysqldumpu
if [ "$?" -eq 0 ]
then
	#zabaleni celeho adresare /var/lib/mysql
	sleep 1
	/bin/systemctl stop mariadb.service
	RvLog "zastaveni mariadb"
	sleep 1
	tar czpf "$backupDir/mysql-${todayDate}.tgz" -C /var/lib/ mysql
	RvLog "tar /var/lib/mysql"
	sleep 1
	/bin/systemctl start mariadb.service
	RvLog "spusteni mariadb"
	cd "$backupDir"
	RvLog "cd ($backupDir)"

	#kontrola navratove hodnoty cd
	if [ "$?" -eq 0 -a -f "$backupName" ]
	then

		#spusteni pozadovanych sluzeb
		for serviceName in ${serviceArray[@]}
		do
			/bin/systemctl start "$serviceName"
			RvLog "spusteni sluzby ($serviceName)"
			sleep 1
		done

		#vytvori zip soubor, pokud byl dump uspesny
		zip "${backupName}.zip" "$backupName" 
		RvLog "zazipovani mysqldumpu dobehlo ($backupDir/${backupName}.zip)"
	
		#odstraneni dump souboru, pokud bylo zipovani uspesne
		if [ "$?" -eq 0 ] && [ -f "$backupName" ]
		then
			rm "$backupName"
			RvLog "odstraneni nekomprimovane zalohy databaze ($backupDir/$backupName)"
		else
			RvLog "zipovani mysqldumpu se nepodarilo ($backupDir/$backupName)"
		fi
	fi
	cd - 
	RvLog "cd -"
fi


#kontrola dostatecneho mnozstvi zaloh
if [ $(find "$backupDir" -name "*.zip" | wc -l) -gt "$backupLimit" ]
then
	#odstraneni zaloh starsich nez $backupLimit
	find "$backupDir" -type f -mtime +"$backupLimit" -exec rm {} \;
	RvLog "odstraneni starych zaloh z ($backupDir)"
else
	LogError "POZOR - nedostatecny pocet zaloh zabbixu"
fi


MailSend
Log "OK - zalohovani dokonceno"
exit 0
