#!/bin/bash
yum -y install epel-release
sleep 1
sed -i -e 's/enabled=1/enabled=0/g' /etc/yum.repos.d/epel.repo
sleep 1
yum --enablerepo=epel -y install atop
sleep 1
chkconfig atop on
sleep 1
service atop start
