#!/bin/bash
#mooster scriptu, ktery doplni polozku mail pomoci uzivatelskeho jmena nacteneho z domeny
#pomoci wbinfo POZOR, domena pro maily i base DN pro ldap jsou psane natvrdo
#druhy for slouzi k tomu, ze prohleda skupinu, nacte jeji cleny a zmeni jim mail na jinou domenu
for mail_user in $(wbinfo -u)
do
	{
		echo "dn: cn="$mail_user",cn=users,dc=workgroup,dc=local"
		echo "changetype: modify"
		echo "replace: mail"
		echo "mail: $mail_user@zvu.cz"
	} > ~/mail.ldif
	
	ldbmodify -H /var/lib/samba/private/sam.ldb ~/mail.ldif
done

for engin_user in $(samba-tool group listmembers engin)
do
	{
		echo "dn: cn="$engin_user",cn=users,dc=workgroup,dc=local"
		echo "changetype: modify"
		echo "replace: mail"
		echo "mail: $engin_user@zvuengineering.cz"
	} > ~/mail.ldif
	
	ldbmodify -H /var/lib/samba/private/sam.ldb ~/mail.ldif
done
