#!/bin/bash
#slouzi pro optimalizaci vsech tabulek v dane databazi
mysqlUser="zabbix"
mysqlPassword="Xb765Af"
mysqlDatabase="zabbix"

for table in $(mysql -u "$mysqlUser" -p"$mysqlPassword" "$mysqlDatabase" -s -e "show tables;")
do 
	mysql -u "$mysqlUser" -p"$mysqlPassword" "$mysqlDatabase" -s -e "OPTIMIZE TABLE $table;"
done
