#!/bin/bash
#rsync-convert - pomaha konvertovat zalohu z hardlinku na backupdir

scriptName="rsync-convert"

#parametry predavane rsyncu, radeji primo ve scriptu nez v configu, --delete, --backup-dir a podobne nelze takto predavat, musi byt natvrdo na radku rsyncu - buh vi proc
rsyncOptions="-rltgoDAuv"

#posledni, aktualni zaloha do ktere se hrne rsyncem, z ni se hardlinkuje zbytek
lastBackup="last"
echo "Nastavena promenna lastBackup na [$lastBackup]"
listFile="_rsync.list"
echo "Nastavena promenna lastFile na [$listFile]"
sourceTarget="/mnt/old"
echo "Nastavena promenna sourceTarget na [$sourceTarget]"
backupTarget="/mnt/new"
echo "Nastavena promenna backupTarget na [$backupTarget]"
backupDir="$backupTarget/last"
echo "Nastavena promenna backupDir na [$backupDir]"

while read backupFolder
do
        echo "zpracovavam slozku $backupFolder"
        backupItem="$sourceTarget/$backupFolder"
        echo "Nastavena promenna backupItem na [$backupItem]"
        archiveDir="$backupTarget/$backupFolder"
        echo "Nastavena promenna archiveDir na [$archiveDir]"
        mkdir "$archiveDir"
        rsyncList="$backupTarget/$listFile"
        echo "Nastavena promenna rsyncList na [$rsyncList]"
        archiveList="$archiveDir/$listFile"
        echo "Nastavena promenna archiveList na [$archiveList]"

        echo -e "\n##########$(date) - $backupItem" >> "$rsyncList"
        rsync "$rsyncOptions" --delete --backup --backup-dir="$archiveDir" "$backupItem"/* "$backupDir" >> "$rsyncList"
        echo "dokonceno zalohovani rsync slozky - ($backupItem)"
        mv "$rsyncList" "$archiveList"

done < rsync-convert.list

#provede zapsani zmen na disky
sync
echo "Sync disku"

MailSend
echo "OK - ($scriptName) zalohovani dokonceno"
exit 0
