#!/bin/bash
#script pro kontrolu a kompilaci sieve scriptu

#provede zalohu
if [ -e /usr/local/scripty/backup ]
then
	/usr/local/scripty/backup
	if find . -mindepth 1 -maxdepth 1 -name "*.sieve" -exec sievec {} \;
	then
		echo "OK"
	else
		echo "nastal problem pri kontrole scriptu sieve"
	fi
else
	echo "POZOR - nenalezen zalohovaci script"
fi
