#!/bin/bash

case $1 in
	up)
	amixer set Master 2+
	;;
	down)
	amixer set Master 2-
	;;	
	mute)
	amixer set Master toggle
	;;
	*)
	echo "Usage volume {up|down|mute}"
esac

STATUS=$(amixer sget Master | awk '$1 == "Mono:" { print $NF; }')

if [ $STATUS = '[off]' ]; then
    VOLUME=MUTED
    ICON=audio-volume-muted-symbolic
else
    VOLUME=$(amixer sget Master | sed '/^ *Mono: /{s/^.*\[\(.*\)%\].*/\1/;p;};d;')
    if [ $VOLUME -lt 33 ]; then
        ICON=audio-volume-low-symbolic
    elif [ $VOLUME -lt 66 ]; then
        ICON=audio-volume-medium-symbolic
    else
        ICON=audio-volume-high-symbolic
    fi
    VOLUME="${VOLUME}%"
fi
/usr/bin/notify-send "Volume Control" "$VOLUME" -i $ICON -t 2
