#!/bin/bash
scriptName=xfce4-panel

notify()
{
	notify-send "$scriptName" "$1" -i xfce4-panel -t 3
}

xfconf-query -c xfce4-panel -p /panels/panel-0/autohide -T

panelState=$(xfconf-query -c xfce4-panel -p /panels/panel-0/autohide)

[ "$panelState" = false ] && notify "is now visible" || notify "will disappear"
