#!/bin/bash
#inicializacni script pro nahrani a nastaveni rsync stahovani na server
homeDir="/usr/local/scripty/home"
sbinDir="/usr/local/sbin"
bashFile="$HOME/.bashrc"
# omezeni seznamu defaultnich souboru ne pouzivane
#defaultList="server-backup zabbix-backup mysql-backup samba-backup rsync-backup postgresql-backup check-server"
defaultList="server-backup mysql-backup postgresql-backup"


#_PROMENNE
scriptName="initialize"


#v pripade, ze je script spousten ze slozky pracovni, nastavi se mu jine cesty, nez pri spusteni pres cron
if [ "$(echo $PWD | grep -c pracovni)" -eq 0 ] && [ "$(echo $0 | grep -c pracovni)" -eq 0 ]	
then
	scriptDir="/usr/local/scripty" #cesta ke scriptu
        verbose=0
	deBug=0
else
	scriptDir="/usr/local/scripty/pracovni" #cesta ke scriptu
	verbose=1
	deBug=1
fi

#spousti se pouze pod rootem
if [ "$UID" -eq 0 ]
then
	#stazeni obsahu ze serveru
	rsync -av --delete monitoring.comarr.cz::scripty /usr/local/scripty
	echo "Provedeno stazeni souboru ze serveru Monitoring"
else
	echo "Pozor - prvotni spusteni je nutne spustit jako root"
fi


#_LOGOVANI
. "$scriptDir/funkce"
Log "Zacatek scriptu"
CheckDir "$pidDir"
echo "$$" > "$startFile"
RvLog "start file set to ($$)"

#spousti se pouze pod rootem
if [ "$UID" -eq 0 ]
then
	[ ! -d "$logFile" ] || rm -r "$logFile"
	RvLog "odstraneni stare slozky $logFile"
	Log "kontrolni cast scriptu"
	CheckDir "$configDir"
	CheckDir "$pidDir"
	CheckDir "$pipeDir"
	CheckDir "$scriptDir"
	CheckDir "$scripty"
	Log "nalinkovani scriptu do /usr/local/bin"
    #nalinkuje vsechny scripty ve slozce $scriptDir do slozky $sbinDir
	for script in $(find "$scriptDir" -maxdepth 1 -mindepth 1 -type f )
	do
		ln -sf "$script" "$sbinDir"
		RvLog "vytvoren symlink ($script)"
	done

	Log "konfigurace cronu a logrotate"
	[ -h "/etc/logrotate.d/scripty" -a -e "/etc/logrotate.d/scripty" ] ||\
        ln -sf /usr/local/scripty/etc/logrotate.d/scripty /etc/logrotate.d/scripty	
	RvLog "ln -sf /usr/local/scripty/etc/logrotate.d/scripty /etc/logrotate.d/scripty"


	#vytvoreni pole ze seznamu scriptu
	scriptsARRAY=($(echo "$defaultList"))
	Log "nacteno pole scriptsARRAY ($scriptsARRAY)"

	#prechod na /usr/local/scripty
	ln -sf /usr/local/scripty/script-downloader /etc/cron.hourly/
	RvLog "ln -sf /usr/local/scripty/script-downloader /etc/cron.daily/"

	#nalinkuje scripty do /etc/cron.daily
	for script in ${scriptsARRAY[@]}
	do
		ln -sf /usr/local/scripty/"$script" /etc/cron.daily/
		RvLog "ln -sf /usr/local/scripty/cronrun /etc/cron.daily/"
	done
	Log "kontroly dokonceny"

	#doplneni aliasu scr
	if [ -e "$bashFile" ] && [ "$(grep -c 'alias scr' $bashFile)" -eq 0 ]
	then
		echo "alias scr='screen -d -R'" >> "$bashFile"
		RvLog "doplnen alias scr do ($bashFile)"
	else
		Log "soubor ($bashFile) je aktualni"
	fi
fi


#nalinkuje vsechny soubory v $homeDir do domovske slozky konkretniho uzivatele
for file in $(ls -a "$homeDir" | grep -v "\." | grep -v "ssh")	
do
	ln -sf "$homeDir/$file" ~/.$file
	RvLog "vytvoren symlink ($homeDir/$file)"
done


MailSend
exit "$rv"
